### PR TITLE
- Added UNode for Comet search engine

### PR DESCRIPTION
**Pull request by cguetot**

### CODE REVIEW

**Comment by StSchulze** [comment]
Hi Carlos,

thanks so much for working on the Comet implementation, this would definitely be a great addition to Ursgal!

I didn't manage yet to have a really close look into the code, but from a first glance, there are a couple of things that need some work (some are probably easier to be done by us, but a few things would be great if you would have time for them as well):

1. There are a lot of stylistic changes in your pull request (removed spaces and stuff like that), which makes it a bit more difficult to review the important changes, especially in the uparams. If it's not too complicated, would you mind removing those stylistic changes (for now)?

2. There is a bit of work required with how the search parameters are implemented (in the wrapper and in uparams). I will work on this, when I find a free minute.

3. The tests are failing because of the parameter "mono_link_definition" in uparams. You have added an empty string in the "available_in_unode" list which throws the error since there is no wrapper with that name. If you could remove that, the tests should work.

4. Besides this, I saw that you implemented the conversion from the pep.xml output into .csv format in the postflight. We generally try to have this type of larger format conversion as a separate node. For example, the XTandem .xml to .csv conversion is in the xtandem2csv_1_0_0 node. It would be great to have the same for Comet, especially since the pep.xml format is used by some other tools as well, so a generalized pep.xml converter would be helpful. If you have the time to put the conversion part into a separate node (which leaves the postflight for Comet pretty much empty then), that would be awesome.

Thanks again for working on this with us and just let us know if you have any questions or if you generally don't really have time to work on these points.

Best,
Stefan

**Comment by cguetot** [comment]
Hi Stefan,

Thanks for letting me contribute to this project.

- After reading your comments, I think I can work on items 1 and 3. 

- Regarding item 4, I can also make the write the UNode, but I do not know how to integrate it into the Comet's postflight section right now.  I don't see any xtandem2csv_1_0_0 calls from any xtandem Node, e.g., xtandem_vengace, so I guess you manage it from another part.  

Since I can not complete all requests, should I remove the pull request?  Do you take the changes from my forked branch and finish it?

Carlos

**Comment by StSchulze** [comment]
Hi Carlos,

I think it's fine to keep this as a pull request here, this way it's a good reminder and we can easily pull it from here and modify it.

Regarding the converter, it's true that it's not directly called in the postflight of the engine, but as a separate step. In principle, converter nodes can be called using the `convert()` function of the `ucontroller`. But we can take care of that part. Having the conversion as a standalone script (i.e. a resources file) would already be great, putting together the wrapper is easy then.

Thanks again,
Stefan

**Comment by StSchulze** [comment]
Hi Carlos,

great, thanks.
I'm sorry that this is taking a while but I'll work on it next week.

Best,
Stefan

**Comment by StSchulze** [comment]
Hi Carlos,

I have modified your PR a bit and pushed it as a new branch for not: feature/comet_2019_01
I still need to work on 2., but for now it should have the same functionality as your PR.
Therefore, I'll close this here for now and will then open a new PR from the branch as soon as I complete 2.

Thanks again,
Stefan

**Pull request closed without merging**
