### PR TITLE
Customizable SVM for PSM post-processing

### PR DESCRIPTION
**Pull request by LKremer**
Introduces a new uNode that can post-process search results in a similar manner to Percolator. SVM parameters (e.g. the kernel) can be changed via the UController params.

to do:
- add documentation
- add tests
- extend basic functionality with more experimental features

### CODE REVIEW

**Comment by fu** [comment]
looks cool Lukas! Unfortunately still has conflicts with uparams :( 
Can you fix this ?

**Comment by LKremer** [comment]
Sure, I'll fix it on the week end!

**Comment by StSchulze** [comment]
Hi Lukas,
I'm sorry, I had to fix a bug in uparams, now it's conflicting with you version again :/

**Comment by LKremer** [comment]
No problem. My quick merge attempt failed, I'll try to fix it when I'm at my work station.

**Comment by LKremer** [comment]
Should be fixed now!

**Pull request merged**
