### PR TITLE
Update to 0.6.5

### PR DESCRIPTION
**Pull request by StSchulze**
- Added ThermoRawFileParser for conversion of .raw to .mzML/.mgf
- Added pGlyco 2.2.0, including pParse 2.0 and pGlycoFDR 2.2.0
- Added latest version of MSGF+ (version 2019.04.18) 
   and MSFragger (version 20190222)

### CODE REVIEW

**Comment by cguetot** [comment]
Hi, 
I am trying to install this pull-request. However, I got this message for msgfplus

````
Executable for msgfplus_v2019_04_18 is not available on your system
[ -<HTPP>- ] Downloading files from https://www.sas.upenn.edu/~sschulze/ursgal_resources/ursgal/resources/platform_independent/arc_independent/msgfplus_v2019_04_18/msgfplus_v2019_04_18.md ...
[ -<HTPP>- ] Saved file as C:\Users\carlos\Documents\Projects\BMC\ursgal\src\ursgal\resources\platform_independent\arc_independent\msgfplus_v2019_04_18\msgfplus_v2019_04_18.md
Remove tmp file: C:/Users/carlos/Documents/Projects/BMC/ursgal/src/ursgal/resources/platform_independent/arc_independent/msgfplus_v2019_04_18/msgfplus_v2019_04_18.md

        [ WARNING ] md5 of online repository for engine msgfplus_v2019_04_18 differs from
        [ WARNING ] md5 in knowledge base, exiting now!!!
        [  INFO   ] Please contact the Ursgal team!
````

**Comment by StSchulze** [comment]
Hi,
thanks for letting us know.
The md5 error should be solved now.

**Comment by MKoesters** [comment]
Regarding the second error, setuptools has no log module.
I introduced this on accident, when switching from distutils to setuptools.
As a quick fix, removing this line should be fine.
@StSchulze Can you substitute this line by a print statement or similar in your pull request or should I open a separate one?

**Comment by StSchulze** [comment]
Modified it :)

**Comment by cguetot** [comment]
perfect installation 👍 .  It is time to test it.

**Comment by fu** [comment]
looks good :) gj ! 👍

**Comment by MKoesters** [comment]
I can't retrigger the AppVeyor build, can someone else do it?
I uploaded a the new pyQms version, it should work now :)

**Comment by StSchulze** [comment]
"retriggered" it ;)
Looks good, thanks!

**Comment by cguetot** [comment]
After testing for a couple of days, everything looks good here, including the newest version of msgfplus.

**Pull request merged**
