### PR TITLE
Improved pymzML compatibility

### PR DESCRIPTION
**Pull request by JB-MS**
Latest MSGF+ version was added
Some code and output were tidied up 
Added new zip md5 values for some new search engine releases

### CODE REVIEW

**Comment by StSchulze** [comment]
Travis is failing, can you check that?

Otherwise it looks quite nice!
Can you include the changes in the changelog as well to move the version to 0.6.1?

**Comment by JB-MS** [comment]
Should work now, i will update the changelog tomorrow.

Thanks for reviewing!

**Comment by StSchulze** [comment]
the requirements.txt can be updated to install pymzml 2.0 as well, right?

**Comment by JB-MS** [comment]
To change the requirements yet, we have to fix some installation issues for pymzML first...

**Pull request merged**
