### PR TITLE
Wrapper for MzidToTsvConverter for MS-GF+ mzid to tsv/csv conversion

### PR DESCRIPTION
**Pull request by JB-MS**
A new and fast C# based mzid to tsv and subsequently to csv converter for MS-GF+ results. Was tested with MS-GF+ versions '2016_09_16' and '2017_01_27' and yields same results as the Java based version.

Please use (at least) version '2017/07/04' of the converter!

https://github.com/PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter/releases/tag/v1.0_20170704

### CODE REVIEW

**Comment by JB-MS** [comment]
It is not used by default yet, it has to explicitly set in the params. We first should discuss this in the dev meeting.

**Comment by StSchulze** [comment]
Is it correct that the flags '-showDecoy' and '-unroll' are not used?
I guess the default is used then, but I would prefer to ecplicitely print out decoys and unroll the results.

**Comment by JB-MS** [comment]
It may be, that setting the flags are not working correctly at the moment. Nevertheless, so far as I tested it, the results are the same for the Java based and the C# based converter. So all should be as we did it before.

Anyways, I will check it again to make sure, it is correct.

**Comment by StSchulze** [comment]
Hmm, not sure why, but it doesn't work for me so far:

```

        -\-     msgfplus_C_mzid2csv_v2017_07_04 run initialized with BSA1_msgfplus_v2016_09_16.mzid (Wed Jul  5 13:37:25 2017)     -/-

[   run    ] Preparing engine
[   run    ] Starting engine
[ Citation ]
[  Please  ]
[  cite:   ] Kim S, Mischerikow N, Bandeira N, Navarro JD, Wich L, Mohammed S, Heck AJ, Pevzner PA. (2010) The Generating Function of CID, ETD, and CID/ETD Pairs of Tandem Mass Spectra: Applications to Database Search.
[  -----   ]
[ Citation ]
[ PREFLGHT ] Executing preflight sequence ...
[ prefligh ] Execution time 0.000 seconds
[ eXecutio ] Executing command list ...
Traceback (most recent call last):
  File ".\simple_example_search.py", line 95, in <module>
    main()
  File ".\simple_example_search.py", line 83, in main
    force      = False
  File "C:\Program Files\Python 3.5\lib\site-packages\ursgal\ucontroller.py", line 1823, in search
    force      = force,
  File "C:\Program Files\Python 3.5\lib\site-packages\ursgal\ucontroller.py", line 344, in convert_results_to_csv
    output_file_name = output_file_name
  File "C:\Program Files\Python 3.5\lib\site-packages\ursgal\ucontroller.py", line 2812, in execute_unode
    force, engine_name, answer
  File "C:\Program Files\Python 3.5\lib\site-packages\ursgal\ucontroller.py", line 2091, in run_unode_if_required
    json_path = json_path,
  File "C:\Program Files\Python 3.5\lib\site-packages\ursgal\unode.py", line 1352, in run
    report['execution'] = self._execute()
  File "C:\Program Files\Python 3.5\lib\site-packages\ursgal\unode.py", line 455, in _execute
    startupinfo=startupinfo,
  File "C:\Program Files\Python 3.5\lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python 3.5\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

I downloaded the newest zip package from the MSGF+ website and extracted is to the corresponding folder in Ursgal. Initializing the controller also shows me that the converter is available, so I guess it's not the engine itself that cannot be found ...

**Comment by JB-MS** [comment]
Sorry, i forgot to make the Mono call optional.  Thus  is not required under Windows.

**Comment by StSchulze** [comment]
Ok, right

By the way, according to the printout
```
unroll results: False
show decoy: False
```

Would be great if you could fix thoose things ;)

And then the next problem: the spec IDs are not correct (and therefore cannot be mapped to the RT). I think you mentioned this before ... so the version that they have on their site is not the most recent one?

**Comment by JB-MS** [comment]
I can not fix this, it is a problem in the converter itself, i think. But as i said, the result are the same as with the Java version. Have you checked that? However,  I will be in contact with the developers to clarify this.

Make sure to use this version of the converter (see above) to avoid wrong spec ids:

https://github.com/PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter/releases/tag/v1.0_20170704

**Comment by StSchulze** [comment]
I'm sorry, I somehow missed the link the first time you posted it :/

I have tested setting unroll and show decoy to True (i.e. 0) and it shows True in the printout and the results are as expected (unrolled and with decoys when 0), so I would say it works ...

But what I actually meant with fixing it was the mono issue, so making the call optional like for msamanda.

Ok, now regarding checking it if they produce the same results:
well, the results directly after conversion are slightly different, the C version file has more lines (I think because it writes separate lines if a pep maps on different proteins), but after unify_csv the results are the same, so I think it's fine.

However, one more bug with the new version:

```
        -\-     msgfplus_C_mzid2csv_v2017_07_04 run initialized with StS_Hvo_wt_GluC_SN_Big12_20160929_msgfplus_v2017_01_27.mzid.gz (Thu Jul  6 09:38:44 2017)     -/-

[   run    ] Preparing engine
[   run    ] Starting engine
[ Citation ] 
[  Please  ] 
[  cite:   ] Kim S, Mischerikow N, Bandeira N, Navarro JD, Wich L, Mohammed S, Heck AJ, Pevzner PA. (2010) The Generating Function of CID, ETD, and CID/ETD Pairs of Tandem Mass Spectra: Applications to Database Search.
[  -----   ] 
[ Citation ] 
[ PREFLGHT ] Executing preflight sequence ...
[ prefligh ] Execution time 0.000 seconds
[ eXecutio ] Executing command list ...
Using options:
mzid path: "/Users/sschulze/ursgal/example_data/test/msgfplus_v2017_01_27/StS_Hvo_wt_GluC_SN_Big12_20160929_msgfplus_v2017_01_27.mzid.gz"
tsv path: "/Users/sschulze/ursgal/example_data/test/msgfplus_v2017_01_27/StS_Hvo_wt_GluC_SN_Big12_20160929_msgfplus_v2017_01_27.tsv"
unroll results: True
show decoy: True
single result per spectrum: False
Conversion failed: An item with the same key has already been added.
at System.ThrowHelper.ThrowArgumentException (System.ExceptionResource resource) [0x0000b] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0
at System.Collections.Generic.Dictionary`2[TKey,TValue].Insert (TKey key, TValue value, System.Boolean add) [0x0008e] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0
at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0
at PSI_Interface.IdentData.SimpleMZIdentMLReader.ReadPeptideEvidence (System.Xml.XmlReader reader) [0x000d3] in <c35e318121b24d90a706f5888e0514ce>:0
at PSI_Interface.IdentData.SimpleMZIdentMLReader.ReadSequenceCollection (System.Xml.XmlReader reader) [0x00098] in <c35e318121b24d90a706f5888e0514ce>:0
at PSI_Interface.IdentData.SimpleMZIdentMLReader.ReadMzIdentMl (System.Xml.XmlReader reader) [0x001f5] in <c35e318121b24d90a706f5888e0514ce>:0
at PSI_Interface.IdentData.SimpleMZIdentMLReader.Read (System.String path, System.Threading.CancellationToken cancelToken) [0x00079] in <c35e318121b24d90a706f5888e0514ce>:0
at MzidToTsvConverter.MzidToTsvConverter.ConvertToTsv (System.String mzidPath, System.String tsvPath, System.Boolean showDecoy, System.Boolean unrollResults, System.Boolean singleResult) [0x00005] in <aa4e31edbbde478ea61c353a0c4310ee>:0
at MzidToTsvConverter.MzidToTsvConverter.ConvertToTsv (MzidToTsvConverter.ConverterOptions options) [0x0001f] in <aa4e31edbbde478ea61c353a0c4310ee>:0
at MzidToTsvConverter.Program.Main (System.String[] args) [0x00026] in <aa4e31edbbde478ea61c353a0c4310ee>:0
Traceback (most recent call last):
  File "do_it_all_folder_wide_single_validation_semienzyme.py", line 167, in <module>
    target_decoy_database = sys.argv[3],
  File "do_it_all_folder_wide_single_validation_semienzyme.py", line 113, in main
    converted_result = uc.convert_results_to_csv(input_file=search_result)
  File "/Users/sschulze/ursgal/example_data/test/ursgal/ucontroller.py", line 344, in convert_results_to_csv
    output_file_name = output_file_name
  File "/Users/sschulze/ursgal/example_data/test/ursgal/ucontroller.py", line 2812, in execute_unode
    force, engine_name, answer
  File "/Users/sschulze/ursgal/example_data/test/ursgal/ucontroller.py", line 2091, in run_unode_if_required
    json_path = json_path,
  File "/Users/sschulze/ursgal/example_data/test/ursgal/unode.py", line 1313, in run
    report['execution'] = self._execute()
  File "/Users/sschulze/ursgal/example_data/test/ursgal/unode.py", line 485, in _execute
    '''.format( self.engine, os.path.relpath(self.exe), self.execute_return_code)
AssertionError: 
  
msgfplus_C_mzid2csv_v2017_07_04 crashed!

  The executable
    ursgal/resources/platform_independent/arc_independent/msgfplus_C_mzid2csv_v2017_07_04/MzidToTsvConverter.exe
  terminated with Error code 42 .
  Inspect the printouts above for possible causes and verify that all input files are valid.
```
Since this seems to be an internal error again (and it works with the old version), we cannot do anything about it ... just wanted to mention it ;)

**Comment by JB-MS** [comment]
I have adjusted the flags, it should be correct now and works as expected. Thanks for testing Stefan!

I get the same error on some files. I have contacted the MS-GF team for a solution.

The mono issue should be also fixed now.

Cheers,
Johannes

**Pull request merged**
