### PR TITLE
added ignore dir named src

### PR DESCRIPTION
**Pull request by kaz-sugi**
src is created by pygcluster

### CODE REVIEW

**Comment by StSchulze** [comment]
This is the pygcluster src, cloned there by install_requirements. Should it be cloned directly into the ursgal folder or rather into resources?

**Comment by JB-MS** [comment]
But this goes into site-packages, right? It should not be in the ursgal directory, anyways. Usage of virtualenv is recommended.

**Comment by StSchulze** [comment]
I agree, it should not be in the ursgal directory, but at the moment
user@localhost:~/ursgal$ pip3.4 install -r requirements.txt
clones the src folder there. So I think the line
-e git+https://github.com/pygcluster/pyGCluster#egg=pyGCluster
in the requirements.txt should be changed ...

**Comment by JB-MS** [comment]
Should be fixed now.

**Pull request merged**
