### PR TITLE
Do not use my name!

### PR DESCRIPTION
**Pull request by kaz-sugi**
I did not and do not and will not agree about ursgal development.
I'm not the ursgal developer.
If you use my name in other parts, please delete it. I checked and found it just in two scripts.

### CODE REVIEW

**Comment by fu** [comment]
You are not a ursgal developer, ok, but all the uparams changes that are important for your project are from you, aren't they ? I found 10 pull requests from your part that were merged into this project... 
the docu says: "Copyright 2014-2015 by authors and **contributors** in alphabetical order" and you did contribute, right ?

Anyways, if you have a big problem with having your name on the readme (or similar), maybe we have to think how to remove all your code from ursgal so you can truly say that nothing in ursgal is from you. That would be sad, but if that is your choice, we have to respect it.

**Comment by kaz-sugi** [comment]
No problem for all. You can decide everything for ursgal, but not about my name.
If you want to delete a code, you can do it. I say that you can do if you want, always.

I did not say that all of codes have to be deleted if my name is nothing. About my code in ursgal, you can use it forever. It's donation. Of course, you also can choose delete.
The point is that I did not agree and you did. Any licence has a condition. About my condition for ursgal contribution, 'do not put my name', not my code.

**Comment by fu** [comment]
Dear Kaz,

I think I do not quite understand the problem. Next to your icon in this discuss is a line that states 
"kaz-sugi commented 43 minutes ago" followed by a box that says Contributor (followed by a smiley, a pen and a x). Do you want to have that removed or just the text file ?

Best regards,

.c

**Comment by kaz-sugi** [comment]
I found my name in two files by chance. And I deleted it and sent this pull-request. I do not have other changing.
If you put my name in other doc or other script, please delete, because I could not find other part.

Basically I do not like to write my name into a script. You can see all of my scripts, not only in GitHub. There is no my name in any scripts. This is my style. When I write it, it is the excellent and the beautiful.

I'm sorry. I do not like ursgal structure very much. So I could not accept my name into ursgal, because ursgal is not excellent and not beautiful for me. About which point, I already sent email. If you forgot already, I can write in here.

**Comment by kaz-sugi** [comment]
By the way, I think I must accept for writing my name, if I'm developer or anther of a paper. In this case, I have the responsible.

**Comment by StSchulze** [comment]
Being a contributor doesn't mean that you have to agree on the whole ursgal structure or development and it is also not the same as being an author or developer. It just means that you contributed code, which you did, and that you take responsibility for this contributed code.
The names in the documentation should provide some transparency, but if you want your contributions only to be traceable by the GitHub history, I guess that's fine as well.

**Comment by kaz-sugi** [comment]
It is not true about responsibility. In MIT licence, the creator does not have Liability and Warranty.
If I have a responsible for my code in ursgal, I have to delete all of my codes, because I agreed to MIT licence and contributed. This information is on GitHub and Licence.txt in ursgal.
image3

**Comment by StSchulze** [comment]
Sorry, I didn't mean that in a juristic way and was certainly not referring to any liability or warranty.
What I meant is a moral responsibility to provide code that is not harmful and in the ideal case to try to help if problems with the contributed code arise (both to the best of your knowledge).

**Comment by kaz-sugi** [comment]
Ok, about it, no problem. I never accept my code from pull-request by myself. Already my codes were checked by others (always).
I agree about your thinking. However it is wrong that all of people is good persons. This control functions when pull-request is accepted. This work is achieved by developers, not contributors at least. So I can say only 'good luck' as my answer.

**Pull request merged**
