### PR TITLE
Update to Ursgal 0.6.3

### PR DESCRIPTION
**Pull request by StSchulze**
* Added Percolator 3.2.1, including comparison script and changing suffix (also for Percolator 2_08 and qvality)
* changed heatmap_column_order to heatmap_column_positions
* Added MS Amanda version 2_0_0_11219, changed version 2_0_0_10695 to platform_independent
* Added MS-GF+ v2019_01_22.py
* Added Novor version 1_05
* updated docu

### CODE REVIEW

**Comment by fu** [comment]
msamanda_2_0_0_10695 extracted into resource/linux/64bit gives me cant find exe

**Comment by StSchulze** [comment]
Yes, because "changed version 2_0_0_10695 to platform_independent" ;)

**Comment by fu** [comment]
ahh .. in that "Box" folder is, I think not like that but that definitely explains it, thanks :)

**Comment by StSchulze** [comment]
1. On github percolator releases it's 3.02.1, so yeah, I assume they just dropped the .1 in naming the file. So should be correct.
2. Is that the case for all systems or only linux? Would it be possible to include it in install requirements?

**Comment by fu** [comment]
good form my side, requires some1 to have a look on Percolator3

**Comment by StSchulze** [comment]
Also added support for .mzML files converted from .wiff files now

**Pull request merged**
